// import { Satoshi } from "next/font/google";
import ReactQueryProvider from "@/utils/QueryProvider";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
import localFont from '@next/font/local'

const Satoshi = localFont({
  src: [
    { path: '../public/fonts/Satoshi-Black.ttf', weight: '700' },
    { path: '../public/fonts/Satoshi-Bold.ttf', weight: '600' },
    { path: '../public/fonts/Satoshi-Regular.ttf', weight: '400' },
    { path: '../public/fonts/Satoshi-Light.ttf', weight: '300' },
  ],
  variable: '--font-satoshi'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Satoshi.variable} font-sans bg-lightgrayed overflow-hidden`}>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
